# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pic',
            field=models.ImageField(upload_to=b''),
        ),
    ]
