# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 17:11
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20170323_1230'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('objectsvotable', django.db.models.manager.Manager()),
            ],
        ),
    ]
