# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20170323_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pic',
            field=models.ImageField(upload_to='oss/static/img'),
        ),
        migrations.AlterField(
            model_name='author',
            name='pro_pic',
            field=models.ImageField(upload_to='oss/static/img'),
        ),
    ]
