# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20170323_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='article',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='article',
            name='vote_score',
        ),
    ]
