# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20170323_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pic',
            field=models.ImageField(upload_to='/img/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='pro_pic',
            field=models.ImageField(upload_to='/img/'),
        ),
    ]
