# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20170323_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Hockey', 'Hockey'), ('Soccer', 'Soccer'), ('Basketball', 'Basketball'), ('Baseball', 'Baseball'), ('Football', 'Football'), ('College Hockey', 'College Hockey'), ('College Soccer', 'College Soccer'), ('College Basketball', 'College Basketball'), ('College Baseball', 'College Baseball'), ('College Football', 'College Football'), ('other', 'other')], default='other', max_length=30),
        ),
    ]
